name: "Update Games"
on:
  workflow_dispatch:

jobs:
  deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Script
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          python ./scripts/update_games.py "$SUPER_SECRET"
      - name: Commit changes
        if: success()
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ./plugin.json
          git commit -m "Update games listing"
          git push
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ github.token }}
